export default [
  { path: '/', redirect: '/login' },
  { path: '/login', component: () => import('@/pages/Login.vue') },
  { path: '/dashboard', component: () => import('@/pages/Dashboard.vue') },
  { path: '/page-menu-2', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/page-menu-3', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/page-menu-4', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/page-menu-5', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/page-menu-6', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/page-menu-7', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/page-menu-8', component: () => import('@/pages/UnderConstruction.vue') },
  { path: '/structure', component: () => import('@/pages/Structure.vue') },
  { path: '/asup', component: () => import('@/pages/Asup.vue') },
  { path: '/divisions/:UUID', component: () => import('@/pages/Division.vue') },
]